sudo: required
services:
  - docker

before_install:
  - docker build -t mendespedro/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mendespedro/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-sa-east-1-478855457555"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_KEY
